<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Title</title>
</head>
<body>
<script>
  (function (window) {
    const PENDING = 'pending'
    const RESOLVED = 'resolved'
    const REJECTED = 'rejected'

    function MyPromise(executor) {
      const self = this//储存this
      this.status = PENDING//初始化状态为pending
      this.data = undefined//初始化结果数值为undefined
      this.callback = []//每个元素的结构：{onResolved() {}, onRejected() {}}

      function resolve(value) {
        //只能更改一次状态
        if (self.status !== PENDING) {
          return
        }
        //状态改为resolved
        self.status = RESOLVED
        //储存value的数据
        self.data = value
        //如果有待执行的callback函数，立即异步执行回调函数
        if (self.callback.length > 0) {
          setTimeout(() => { // 放入队列中执行所有成功的回调
            self.callback.forEach(callbackObj => {
              callbackObj.onResolvedSave()
            })
          })
        }
      }

      function reject(reason) {
        //只能更改一次状态
        if (self.status !== PENDING) {
          return
        }
        //将状态更改为rejected
        self.status = REJECTED
        //保存数据
        self.data = reason
        //有待执行的callback回调立刻异步执行回调
        if (self.callback.length > 0) {
          setTimeout(() => {// 放入队列中执行所有失败的回调
            self.callback.forEach(callbackObj => {
              callbackObj.onRejectedSave()
            })
          })
        }
      }

      //立即同步执行executor
      try {//如果执行器抛出异常，promise对象变为rejected
        executor(resolve, reject)
      } catch (error) {
        reject(error)
      }
    }

    /**
     * 原型上的then方法，规定根据promise状态来执行的回调函数
     */
    MyPromise.prototype.then = function (onResolved, onRejected) {
      onResolved = typeof onResolved === 'function' ? onResolved : value => value
      //实现异常穿透，promise如果是rejected都直接抛出异常
      onRejected = typeof onRejected === 'function' ? onRejected : reason => {
        throw reason
      }

      const self = this
      return new MyPromise((resolve, reject) => {
        /**
         * 1.如果执行抛出异常，return的promise会失败，失败的reason是error
         * 2.如果回调函数返回值非promise，return的promise就会成功，value就是返回的值
         * 3.如果回调函数返回的是promise，return的promise就是这个promise的结果
         */
        function handle(callback) {
          try {
            const result = callback(self.data)
            // 3.如果回调函数返回的是promise，return的promise就是这个promise的结果
            if (result instanceof MyPromise) {
              //简便写法： result.then(resolve, reject)
              result.then(value => resolve(value)
                , reason => reject(reason)
              )
            } else {
              // 2.如果回调函数返回值非promise，return的promise就会成功，value就是返回的值
              resolve(result)
            }
          } catch (error) {
            // 1.如果执行抛出异常，return的promise会失败，失败的reason是error
            throw error
          }
        }

        if (self.status === PENDING) {
          self.callback.push({
            //不能仅仅只放onResolved函数，因为onResolved的执行结果
            // 会影响返回的promise的状态，需要用handle包装判断下
            onResolvedSave() {
              handle(onResolved)
            },
            onRejectedSave() {
              handle(onRejected)
            }
          })
        } else if (self.status === RESOLVED) { //当前状态是resolved/rejected，执行回调（异步）
          setTimeout(() => {
            handle(onResolved)
          })
        } else {
          setTimeout(() => {
            handle(onRejected)
          })
        }
      })
    }

    /**
     * promise原型上的catch方法，相当于不规定成功回调的then方法
     */
    MyPromise.prototype.catch = function (onRejected) {
      return this.then(undefined, onRejected)
    }

    /**
     *Promise.resolve(value)方法返回一个以给定值解析后的Promise 对象。
     * 如果这个值是一个 promise ，那么将返回这个 promise ；
     * 如果这个值是thenable（即带有"then" 方法），返回的promise会“跟随”这个thenable的对象，采用它的最终状态；
     * 否则返回的promise将以此值完成。此函数将类promise对象的多层嵌套展平。
     */
    MyPromise.resolve = function (value) {
      return new MyPromise((resolve, reject) => {
        //如果传入的value是promise，直接返回此promise
        if (value instanceof MyPromise) {
          //相当于返回此promise
          value.then(resolve, reject)
        } else {
          resolve(value)
        }
      })
    }

    /**
     * promise上的reject方法，返回一个失败的promise
     */
    MyPromise.reject = function (reason) {
      return new MyPromise((resolve, reject) => {
        reject(reason)
      })
    }

    /**
     * promise.all方法
     */
    MyPromise.all = function (myPromises) {
      const values = new Array(myPromises.length)
      let i = 0
      return new MyPromise((resolve, reject) => {
        myPromises.forEach((p, index) => {
          MyPromise.resolve(p).then(
            value => {
              i++
              values[index] = value
              if (i === myPromises.length) {
                resolve(values)
              }
            },
            reason => {
              reject(reason)
            }
          )
        })
      })
    }

    /**
     *promise.race方法
     */
    MyPromise.race = function (myPromises) {
      return new MyPromise((resolve, reject) => {
        myPromises.forEach((p) => {
          MyPromise.resolve(p).then(
            value => {
              resolve(value)
            },
            reason => {
              reject(reason)
            }
          )
        })
      })
    }

    window.MyPromise = MyPromise
  })(window)
</script>
</body>
</html>